### ISSUE TITLE
Fix major new C error for CRAN

### ISSUE THREAD

**Issue by hendersontrent** [hendersontrent/Rcatch22#49]
Must be done by 28/09/2024

**Comment by eddelbuettel** [comment]
I got curious about this odd-looking compiler error and I have a fix -- on my system `g++-14` reproduces what CRAN reported, and this goes away after a simple change.  This looks like more of an error / bad temporary in `g++` (maybe only inder lto as CRAN uses).

**Comment by hendersontrent** [comment]
Hi @eddelbuettel , thanks for taking the time to comment! I would greatly appreciate a PR. A lot of the C code in this package is legacy code from a non-R programmer that I ported across, and so any help with solving this CRAN report would be a great help.

**Comment by eddelbuettel** [comment]
Ok -- PR #50 is there now.  You may want to check the before/after, it was pretty straightforward for me by wiring up `g++-14` as the default compiler via `~/.R/Makevars`.

(We could/should maybe follow-up with another PR to remove the .o and .so files from src/, we usually do not commit those.)
